<a href="https://colab.research.google.com/github/nicolem100/HELLO-WORLD1/blob/master/Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import of the Titanic Dataset

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Import the titanic dataset

In [5]:
dataset=pd.read_excel("titanic.xlsx")

In [3]:
dataset.head()

Survived  Pclass  ... Parents/Children Aboard     Fare
0         0       3  ...                       0   7.2500
1         1       1  ...                       0  71.2833
2         1       3  ...                       0   7.9250
3         1       1  ...                       0  53.1000
4         0       3  ...                       0   8.0500

[5 rows x 8 columns]

In [8]:
y=dataset.iloc[:,0].values
X=dataset.iloc[:,1:].values

In [9]:
print(X)
print(y)

[[3 'Mr. Owen Harris Braund' 'male' ... 1 0 7.25]
 [1 'Mrs. John Bradley (Florence Briggs Thayer) Cumings' 'female' ... 1 0
  71.2833]
 [3 'Miss. Laina Heikkinen' 'female' ... 0 0 7.925]
 ...
 [3 'Miss. Catherine Helen Johnston' 'female' ... 1 2 23.45]
 [1 'Mr. Karl Howell Behr' 'male' ... 0 0 30.0]
 [3 'Mr. Patrick Dooley' 'male' ... 0 0 7.75]]
[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1
 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0 0
 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0
 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0 0
 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1 1
 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0 0 0
 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1

Delete the name column fromthe future vector

In [11]:
X=np.delete(X,1,1)
print(X)

[[3 22.0 1 0 7.25]
 [1 38.0 1 0 71.2833]
 [3 26.0 0 0 7.925]
 ...
 [3 7.0 1 2 23.45]
 [1 26.0 0 0 30.0]
 [3 32.0 0 0 7.75]]


In [12]:
X[:,[1,4]]

array([[22.0, 7.25],
       [38.0, 71.2833],
       [26.0, 7.925],
       ...,
       [7.0, 23.45],
       [26.0, 30.0],
       [32.0, 7.75]], dtype=object)